"""
NyayaPath — Crisis & Emergency Resources

Hard-coded emergency helplines and distress resources. These are NEVER
generated by the LLM — they are injected deterministically when the
crisis detection node fires.

All numbers must be verified against current official sources before
shipping.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CrisisResource:
    """A single emergency or crisis helpline."""

    name: str
    number: str
    description: str
    availability: str = "24x7"
    verified_against: str = ""
    verified_on: str = "2024-09-18"


# ---------------------------------------------------------------------------
# Hard-Coded Emergency Resources
# ---------------------------------------------------------------------------

NATIONAL_EMERGENCY = CrisisResource(
    name="National Emergency Number",
    number="112",
    description="Integrated emergency response (Police, Fire, Ambulance)",
    verified_against="Ministry of Home Affairs",
)

TELE_MANAS = CrisisResource(
    name="Tele-MANAS Mental Health Helpline",
    number="14416",
    description="Mental health counselling and crisis support (toll-free)",
    availability="24x7",
    verified_against="Ministry of Health & Family Welfare",
)

TELE_MANAS_TOLL_FREE = CrisisResource(
    name="Tele-MANAS (Alternate Toll-Free)",
    number="1800-891-4416",
    description="Alternate toll-free number for Tele-MANAS",
    availability="24x7",
    verified_against="Ministry of Health & Family Welfare",
)

WOMEN_HELPLINE = CrisisResource(
    name="Women Helpline",
    number="181",
    description="Women in distress — counselling, shelter referral, police assistance",
    verified_against="Ministry of Women and Child Development",
)

POLICE_HELPLINE = CrisisResource(
    name="Police Helpline",
    number="100",
    description="Direct police assistance",
)


# ---------------------------------------------------------------------------
# Aggregated Resources
# ---------------------------------------------------------------------------

CRISIS_RESOURCES: list[CrisisResource] = [
    NATIONAL_EMERGENCY,
    TELE_MANAS,
    TELE_MANAS_TOLL_FREE,
    WOMEN_HELPLINE,
    POLICE_HELPLINE,
]


def format_crisis_response() -> str:
    """Return the complete crisis intervention response.

    This replaces ALL normal processing when crisis is detected. The
    agent stops procedural guidance, acknowledges the seriousness, and
    surfaces only hard-coded helplines.
    """
    lines = [
        "## I hear you, and I want you to know that help is available right now.\n",
        "What you're going through sounds incredibly difficult. Your safety "
        "and well-being are the most important things right now — more "
        "important than any legal question.\n",
        "**Please reach out to one of these services immediately:**\n",
    ]

    for res in CRISIS_RESOURCES:
        lines.append(f"- 📞 **{res.name}**: **{res.number}** — {res.description} ({res.availability})")

    lines.extend([
        "",
        "These are trained professionals who can help. You do not have to "
        "face this alone.",
        "",
        "Once you are feeling safer, I am here to help with any legal "
        "questions you may have.",
        "",
        "---",
        "*This is general educational information only and not legal advice. "
        "Every case is different. You must consult a qualified advocate "
        "before taking any step.*",
    ])

    return "\n".join(lines)
